{
 "title": "KCP / Kyma Environment Broker / v2",
 "tags": [
  "kyma-environment-broker",
  "kcp"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "plan_id",
    "query": "aws : 361c511f-f939-4621-b228-d0fb79a1fe15, azure : 4deee563-e5ec-4731-b9b1-53b42d855f0c, azure_lite : 8cb22518-aa26-44c5-91a0-e669ec9bf443, gcp : ca6e5357-707f-4565-bbbd-b3ab732597c6, openstack : 03b812ac-c991-4528-b5bd-08b303523a63, trial : 7d55d31d-35ae-4438-bf13-6ffdfa107d9f, free : b1a5764e-2ea1-4f95-94c0-2b4538b37b55"
   },
   {
    "name": "error_category",
    "query": {
     "query": "label_values({__name__=~\"kcp_keb_v2_provisioning_result|kcp_keb_v2_deprovisioning_result\", plan_id=~\"$plan_id\"}, error_category)"
    }
   },
   {
    "name": "error_reason",
    "query": {
     "query": "label_values({__name__=~\"kcp_keb_v2_provisioning_result|kcp_keb_v2_deprovisioning_result\", plan_id=~\"$plan_id\", error_category=~\"$error_category\"}, error_reason)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Runtime Business Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total number of instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(kcp_keb_v2_instances_total{service=\"kcp-kyma-environment-broker\"})"
    }
   ]
  },
  {
   "title": "Top 16 number of instances per Global Account ID",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(16, kcp_keb_v2_global_account_id_instances_total{service=\"kcp-kyma-environment-broker\"})",
     "legendFormat": "{{global_account_id}}"
    }
   ]
  },
  {
   "title": "Total number of Global Accounts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kcp_keb_v2_global_account_id_instances_total{service=\"kcp-kyma-environment-broker\"})"
    }
   ]
  },
  {
   "title": "In progress provisioning operations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(kcp_keb_v2_operations_provisioning_in_progress_total{service=\"kcp-kyma-environment-broker\"})"
    }
   ]
  },
  {
   "title": "In progress deprovisioning operations",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(kcp_keb_v2_operations_deprovisioning_in_progress_total{service=\"kcp-kyma-environment-broker\"})"
    }
   ]
  },
  {
   "title": "Success Rate (All)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase_prometheus(kcp_keb_v2_operations_provisioning_succeeded_total[$__range])))/(round(sum(increase_prometheus(kcp_keb_v2_operations_provisioning_failed_total[$__range])))+round(sum(increase_prometheus(kcp_keb_v2_operations_provisioning_succeeded_total[$__range]))))*100",
     "legendFormat": "Provision"
    },
    {
     "expr": "round(sum(increase_prometheus(kcp_keb_v2_operations_deprovisioning_succeeded_total[$__range])))/(round(sum(increase_prometheus(kcp_keb_v2_operations_deprovisioning_failed_total[$__range])))+round(sum(increase_prometheus(kcp_keb_v2_operations_deprovisioning_succeeded_total[$__range]))))*100",
     "legendFormat": "Deprovision"
    }
   ]
  },
  {
   "title": "Provision - Top 3 error category and reason ($plan_id)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, count by (error_category, error_reason) (kcp_keb_v2_provisioning_result{plan_id=~\"$plan_id\"} == 0 unless (kcp_keb_v2_provisioning_result{plan_id=~\"$plan_id\"} offset $__range == 0)))",
     "legendFormat": "{{error_category}} - {{error_reason}}"
    }
   ]
  },
  {
   "title": "Deprovision - Top 3 error category and reason ($plan_id)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 13, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, count by (error_category, error_reason) (kcp_keb_v2_deprovisioning_result{plan_id=~\"$plan_id\"} == 0 unless (kcp_keb_v2_deprovisioning_result{plan_id=~\"$plan_id\"} offset $__range == 0)))",
     "legendFormat": "{{error_category}} - {{error_reason}}"
    }
   ]
  },
  {
   "title": "Provision/Deprovision [$plan_id]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "plan_id"
  },
  {
   "title": "Provision ($plan_id)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase_prometheus(kcp_keb_v2_operations_provisioning_succeeded_total{plan_id=\"$plan_id\"}[$__range]) + increase_prometheus(kcp_keb_v2_operations_provisioning_failed_total{plan_id=\"$plan_id\"}[$__range])))",
     "legendFormat": "Total Provision "
    },
    {
     "expr": "round(sum(increase_prometheus(kcp_keb_v2_operations_provisioning_succeeded_total{plan_id=\"$plan_id\"}[$__range])))",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "round(sum(increase_prometheus(kcp_keb_v2_operations_provisioning_failed_total{plan_id=\"$plan_id\"}[$__range])))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(increase_prometheus(kcp_keb_v2_operations_provisioning_succeeded_total{plan_id=\"$plan_id\"}[$__range])) / (sum(increase_prometheus(kcp_keb_v2_operations_provisioning_succeeded_total{plan_id=\"$plan_id\"}[$__range]) + increase_prometheus(kcp_keb_v2_operations_provisioning_failed_total{plan_id=\"$plan_id\"}[$__range])) > 0 ) *100 or vector(0)",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Provisioning (${plan_id})",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kcp_keb_v2_operations_provisioning_in_progress_total{plan_id=\"$plan_id\", service=\"kcp-kyma-environment-broker\"})"
    }
   ]
  },
  {
   "title": "Provision Duration ($plan_id)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(kcp_keb_v2_provisioning_duration_minutes_sum{plan_id=\"$plan_id\"}[$__range]))",
     "legendFormat": "Average"
    },
    {
     "expr": "max(avg_over_time(kcp_keb_v2_provisioning_duration_minutes_sum{plan_id=\"$plan_id\"}[$__range]))",
     "legendFormat": "Max"
    },
    {
     "expr": "min(avg_over_time(kcp_keb_v2_provisioning_duration_minutes_sum{plan_id=\"$plan_id\"}[$__range]))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Deprovision (${plan_id} )",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase_prometheus(kcp_keb_v2_operations_deprovisioning_succeeded_total{plan_id=\"$plan_id\"}[$__range]) + increase_prometheus(kcp_keb_v2_operations_deprovisioning_failed_total{plan_id=\"$plan_id\"}[$__range])))",
     "legendFormat": "Total Deprovision "
    },
    {
     "expr": "round(sum(increase_prometheus(kcp_keb_v2_operations_deprovisioning_succeeded_total{plan_id=\"$plan_id\"}[$__range])))",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "round(sum(increase_prometheus(kcp_keb_v2_operations_deprovisioning_failed_total{plan_id=\"$plan_id\"}[$__range])))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(increase_prometheus(kcp_keb_v2_operations_deprovisioning_succeeded_total{plan_id=\"$plan_id\"}[$__range])) / (sum(increase_prometheus(kcp_keb_v2_operations_deprovisioning_succeeded_total{plan_id=\"$plan_id\"}[$__range]) + increase_prometheus(kcp_keb_v2_operations_deprovisioning_failed_total{plan_id=\"$plan_id\"}[$__range])) > 0 ) *100 or vector(0)",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Deprovisioning (${plan_id})",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kcp_keb_v2_operations_deprovisioning_in_progress_total{plan_id=\"$plan_id\", service=\"kcp-kyma-environment-broker\"})"
    }
   ]
  },
  {
   "title": "Deprovision Duration ($plan_id)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(avg_over_time(kcp_keb_v2_deprovisioning_duration_minutes_sum{plan_id=\"$plan_id\"}[$__range]))",
     "legendFormat": "Max"
    },
    {
     "expr": "min(avg_over_time(kcp_keb_v2_deprovisioning_duration_minutes_sum{plan_id=\"$plan_id\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(avg_over_time(kcp_keb_v2_deprovisioning_duration_minutes_sum{plan_id=\"$plan_id\"}[$__range]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Upgrades [$plan_id]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "repeat": "plan_id",
   "collapsed": true,
   "panels": [
    {
     "title": "Upgrade Cluster ($plan_id)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count((kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"}) unless (kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"} offset $__range)) or vector(0)",
       "legendFormat": "Total"
      },
      {
       "expr": "count((kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"}==1) unless (kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"} offset $__range == 1)) or vector(0)",
       "legendFormat": "Succeeded"
      },
      {
       "expr": "count((kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"}==0) unless (kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"} offset $__range == 0)) or vector(0)",
       "legendFormat": "Failed"
      },
      {
       "expr": "count((kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"}==5) unless (kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"} offset $__range == 5)) or vector(0)",
       "legendFormat": "Canceled"
      },
      {
       "expr": "count((kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"}==1) unless (kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"} offset $__range == 1)) / count((kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"}) unless (kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"} offset $__range)) * 100 or vector(0)",
       "legendFormat": "Success Rate"
      }
     ]
    },
    {
     "title": "Upgrade Cluster Progressing ($plan_id)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count((kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"}==2) unless (kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"} offset $__range == 2)) or vector(0)",
       "legendFormat": "In Progress"
      },
      {
       "expr": "count((kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"}==3) unless (kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"} offset $__range == 3)) or vector(0)",
       "legendFormat": "Pending"
      },
      {
       "expr": "count((kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"}==4) unless (kcp_keb_v2_upgrade_cluster_result{plan_id=\"$plan_id\"} offset $__range == 4)) or vector(0)",
       "legendFormat": "Canceling"
      }
     ]
    },
    {
     "title": "Upgrade Kyma ($plan_id)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count((kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"}) unless (kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"} offset $__range)) or vector(0)",
       "legendFormat": "Total"
      },
      {
       "expr": "count((kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"}==1) unless (kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"} offset $__range == 1)) or vector(0)",
       "legendFormat": "Succeeded"
      },
      {
       "expr": "count((kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"}==0) unless (kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"} offset $__range == 0)) or vector(0)",
       "legendFormat": "Failed"
      },
      {
       "expr": "count((kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"}==5) unless (kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"} offset $__range == 5)) or vector(0)",
       "legendFormat": "Canceled"
      },
      {
       "expr": "count((kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"}==1) unless (kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"} offset $__range == 1)) / count((kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"}) unless (kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"} offset $__range)) * 100 or vector(0)",
       "legendFormat": "Success Rate"
      }
     ]
    },
    {
     "title": "Upgrade Kyma Progressing ($plan_id)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count((kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"}==2) unless (kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"} offset $__range == 2)) or vector(0)",
       "legendFormat": "In Progress"
      },
      {
       "expr": "count((kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"}==3) unless (kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"} offset $__range == 3)) or vector(0)",
       "legendFormat": "Pending"
      },
      {
       "expr": "count((kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"}==4) unless (kcp_keb_v2_upgrade_kyma_result{plan_id=\"$plan_id\"} offset $__range == 4)) or vector(0)",
       "legendFormat": "Canceling"
      }
     ]
    }
   ]
  },
  {
   "title": "Broker Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC duration [s]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (go_gc_duration_seconds{service=\"kcp-kyma-environment-broker\"})",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (go_goroutines{service=\"kcp-kyma-environment-broker\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Gothreads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (go_threads{service=\"kcp-kyma-environment-broker\"})",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (go_memstats_alloc_bytes{service=\"kcp-kyma-environment-broker\"})",
       "legendFormat": "bytes allocated"
      },
      {
       "expr": "avg by (service) (rate(go_memstats_alloc_bytes_total{service=\"kcp-kyma-environment-broker\"}[1m]))",
       "legendFormat": "alloc rate"
      },
      {
       "expr": "sum by (service) (go_memstats_stack_inuse_bytes{service=\"kcp-kyma-environment-broker\"})",
       "legendFormat": "stack inuse"
      },
      {
       "expr": "sum by (service) (go_memstats_heap_inuse_bytes{service=\"kcp-kyma-environment-broker\"})",
       "legendFormat": "heap inuse"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (process_open_fds{service=\"kcp-kyma-environment-broker\"})",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "DB connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service) (go_sql_stats_connections_idle{service=\"kcp-kyma-environment-broker\"})",
       "legendFormat": "Idle"
      },
      {
       "expr": "avg by (service) (go_sql_stats_connections_max_open{service=\"kcp-kyma-environment-broker\"})",
       "legendFormat": "Max open"
      },
      {
       "expr": "avg by (service) (go_sql_stats_connections_in_use{service=\"kcp-kyma-environment-broker\"})",
       "legendFormat": "In use"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (container) (container_memory_usage_bytes{job=\"kubelet\",pod=~\"kcp-kyma-environment-broker.*\",container!=\"POD\",container!=\"\"})",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "avg by (container) (kube_pod_container_resource_requests_memory_bytes{pod=~\"kcp-kyma-environment-broker.*\"})",
       "legendFormat": "{{container}} - Requests"
      },
      {
       "expr": "avg by (container) (kube_pod_container_resource_limits_memory_bytes{pod=~\"kcp-kyma-environment-broker.*\"})",
       "legendFormat": "{{container}} - Limit"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\",pod=~\"kcp-kyma-environment-broker.*\",container!=\"POD\",container!=\"\"}[1m]))",
       "legendFormat": "{{container}}"
      },
      {
       "expr": "avg by (container) (kube_pod_container_resource_requests_cpu_cores{pod=~\"kcp-kyma-environment-broker.*\"})",
       "legendFormat": "{{container}} - Requests"
      },
      {
       "expr": "avg by (container) (kube_pod_container_resource_limits_cpu_cores{pod=~\"kcp-kyma-environment-broker.*\"})",
       "legendFormat": "{{container}} - Limit"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (namespace) (rate(container_network_receive_bytes_total{pod=~\"kcp-kyma-environment-broker.*\"}[1m])))",
       "legendFormat": "kcp-kyma-environment-broker"
      }
     ]
    }
   ]
  }
 ]
}