// Code generated by mockery v2.43.1. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// RegionReader is an autogenerated mock type for the RegionReader type
type RegionReader struct {
	mock.Mock
}

// Read provides a mock function with given fields: filename
func (_m *RegionReader) Read(filename string) (map[string][]string, error) {
	ret := _m.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 map[string][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string][]string, error)); ok {
		return rf(filename)
	}
	if rf, ok := ret.Get(0).(func(string) map[string][]string); ok {
		r0 = rf(filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRegionReader creates a new instance of RegionReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegionReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegionReader {
	mock := &RegionReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
