
@instance_id=<instance_id>

@plan_id=<instance_id>
@service_id=47c9dcbf-ff30-448e-ab36-d3bad66ba281

@binding_id=<binding_id>

PUT http://localhost:8080/oauth/v2/service_instances/{{instance_id}}/service_bindings/{{binding_id}}?accepts_incomplete=true&accepts_incomplete=true&service_id={{service_id}}&plan_id={{plan_id}}
Content-Type: application/json
X-Broker-API-Version: 2.14

{
  "service_id": "{{service_id}}",
  "plan_id": "{{plan_id}}",
  "parameters": {
    "service_account": false
  }
}

