apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "kyma-env-broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kyma-env-broker.name" . }}
      app.kubernetes.io/instance: {{ .Values.namePrefix }}
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  labels:
    app.kubernetes.io/name: subaccount-sync
  name: subaccount-sync
  namespace: kcp-system
spec:
  mtls:
    mode: PERMISSIVE
  selector:
    matchLabels:
      app.kubernetes.io/name: subaccount-sync