apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth-keb
  namespace: kcp-system
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  jwtRules:
  - issuer: {{ tpl .Values.oidc.issuer $ }}
    jwksUri: {{ tpl .Values.oidc.keysURL $ }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kyma-env-broker.name" . }}
      app.kubernetes.io/instance: {{ .Values.namePrefix }}
