{{- if and .Values.global.secrets.enabled (eq .Values.global.secrets.mechanism "secrets") }}
{{- if eq .Values.manageSecrets true }}
apiVersion: v1
data:
  apiEndpoint: {{ .Values.avs.apiEndpoint | b64enc | quote }}
  apiKey: {{ .Values.avs.apiKey | b64enc | quote }}
  clientId: {{ .Values.avs.clientId | b64enc | quote }}
  oauthPassword: {{ .Values.avs.oauthPassword | b64enc | quote }}
  oauthTokenEndpoint: {{ .Values.avs.oauthTokenEndpoint | b64enc | quote }}
  oauthUserName: {{ .Values.avs.oauthUserName | b64enc | quote }}
  internalTesterAccessId: {{ .Values.avs.internalTesterAccessId | b64enc | quote }}
  externalTesterAccessId: {{ .Values.avs.externalTesterAccessId | b64enc | quote }}
  internalTesterService: {{ .Values.avs.internalTesterService | b64enc | quote }}
  externalTesterService: {{ .Values.avs.externalTesterService | b64enc | quote }}
  groupId: {{ .Values.avs.groupId | b64enc | quote }}
  parentId: {{ .Values.avs.parentId | b64enc | quote }}
  trialApiKey: {{ .Values.avs.trialApiKey | b64enc | quote }}
  trialInternalTesterAccessId: {{ .Values.avs.trialInternalTesterAccessId | b64enc | quote }}
  trialGroupId: {{ .Values.avs.trialGroupId | b64enc | quote }}
  trialParentId: {{ .Values.avs.trialParentId | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.avs.secretName }}
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.edp.secretName }}"
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.edp.secret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cis.v1.secretName | required "please specify .Values.cis.v1.secretName" | quote }}
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  id: {{ .Values.cis.v1.id | required "please specify .Values.cis.v1.id" | b64enc | quote }}
  secret: {{ .Values.cis.v1.secret | required "please specify .Values.cis.v1.secret" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cis.v2.secretName | required "Please specify .Values.cis.v2.secretName" | quote}}
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  id: {{ .Values.cis.v2.id | required "please specify .Values.cis.v2.id" | b64enc | quote }}
  secret: {{ .Values.cis.v2.secret | required "please specify .Values.cis.v2.secret" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cis.accounts.secretName | required "please specify .Values.cis.accounts.secretName" | quote }}
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  id: {{ .Values.cis.accounts.id | required "please specify .Values.cis.accounts.id" | b64enc | quote }}
  secret: {{ .Values.cis.accounts.secret | required "please specify .Values.cis.accounts.secret " | b64enc | quote }}
{{- end }}
{{- end }}