apiVersion: v1
kind: Service
metadata:
  name: {{ include "kyma-env-broker.fullname" . }}
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.global.istio.proxy.port }}
      protocol: TCP
      name: proxy-status
  selector:
    app.kubernetes.io/name: {{ include "kyma-env-broker.name" . }}
    app.kubernetes.io/instance: {{ .Values.namePrefix }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: subaccount-sync
    argocd.argoproj.io/instance: keb
  name: subaccount-sync
  namespace: kcp-system
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.subaccountSync.metricsPort }}
      protocol: TCP
      targetPort: http
    - name: proxy-status
      port: {{ .Values.global.istio.proxy.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: subaccount-sync
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: runtime-reconciler
    argocd.argoproj.io/instance: keb
  name: runtime-reconciler
  namespace: kcp-system
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.runtimeReconciler.metricsPort }}
      protocol: TCP
      targetPort: http
    - name: proxy-status
      port: {{ .Values.global.istio.proxy.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: runtime-reconciler
