{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
  name: {{ include "kyma-env-broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "kyma-env-broker.labels" . | indent 8 }}
{{- end }}
{{- if and (.Capabilities.APIVersions.Has "operator.victoriametrics.com/v1beta1/VMServiceScrape") .Values.vmscrapes.enabled }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
  name: {{ include "kyma-env-broker.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - attach_metadata: {}
    port: http
    interval: {{ .Values.vmscrapes.interval }}
    scrapeTimeout: {{ .Values.vmscrapes.scrapeTimeout }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "kyma-env-broker.labels" . | indent 8 }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: subaccount-sync
  name: subaccount-sync
  namespace: kcp-system
spec:
  endpoints:
    - attach_metadata: {}
      interval: 30s
      port: http
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - kcp-system
  selector:
    matchLabels:
      app.kubernetes.io/name: subaccount-sync
{{- end }}
