name: pull-build-and-test-images

on:
   pull_request_target:
      types: [ opened, edited, synchronize, reopened, ready_for_review ]

permissions:
   id-token: write
   contents: read
jobs:
   kyma-environment-broker-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with: 
      name:  kyma-environment-broker
      dockerfile: Dockerfile.keb
      context: .

   archiver-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-archiver-job
         dockerfile: Dockerfile.job
         context: .
         build-args: BIN=archiver

   environments-cleanup-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environments-cleanup-job
         dockerfile: Dockerfile.job
         context: .
         build-args: BIN=environmentscleanup

   deprovision-retrigger-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-deprovision-retrigger-job
         dockerfile: Dockerfile.job
         context: .
         build-args: BIN=deprovisionretrigger

   expirator-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-expirator-job
         dockerfile: Dockerfile.job
         context: .
         build-args: BIN=expirator

   runtime-reconciler-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-runtime-reconciler
         dockerfile: Dockerfile.runtimereconciler
         context: .
         build-args: BIN=runtime-reconciler

   subaccount-cleanup-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-subaccount-cleanup-job
         dockerfile: Dockerfile.job
         context: .
         build-args: BIN=accountcleanup

   subaccount-sync-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-subaccount-sync
         dockerfile: Dockerfile.subaccountsync
         context: .
         build-args: BIN=subaccount-sync

   run-install-keb-chart-tests:
      permissions:
         contents: read
      needs: [kyma-environment-broker-image, archiver-image, environments-cleanup-image, deprovision-retrigger-image, expirator-image, runtime-reconciler-image, subaccount-cleanup-image, subaccount-sync-image]
      uses: "./.github/workflows/run-keb-chart-install-tests-reusable.yaml"
      if: ${{ !github.event.pull_request.draft }}
      with:
         last-k3s-versions: 3
         release: "false"
         version: ${{ github.event.pull_request.number }}
