# Call this workflow from other jobs to execute unit tests in the current context

name: Run unit tests (reusable)

on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: "admin",
          POSTGRES_PASSWORD: "nimda",
          POSTGRES_DB: "broker",
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up go environment
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Run tests
      run: make verify
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_USER: "admin",
        POSTGRES_PASSWORD: "nimda",
        POSTGRES_DB: "broker",