name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    # Trigger for Pull Request
    branches: [ "main" ]

permissions: write-all

jobs:
  run-unit-tests:
    uses: "./.github/workflows/run-unit-tests-reusable.yaml"
