# Call this workflow from other jobs to execute unit tests in the current context

name: Run unit tests (reusable)

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # implementation at 'source/generic_make_go.mk'
    - name: Run tests
      run: make release